name: Trigger auto deployment for container-app-lec4wcdmksi4w

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-lec4wcdmksi4w-AutoDeployTrigger-29b3c75a-8420-4231-b15f-3d7dae7ab278.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPLEC4WCDMKSI4W_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPLEC4WCDMKSI4W_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPLEC4WCDMKSI4W_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPLEC4WCDMKSI4W_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPLEC4WCDMKSI4W_REGISTRY_PASSWORD }}
          containerAppName: container-app-lec4wcdmksi4w
          resourceGroup: flaskbasic945bb426
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


